# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://mblanke70.github.io
baseurl:             'simple-blog-2022'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Malte Blanke
  url:               https://github.com/mblanke70
  email:             malte.blanke@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
